apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-web-deployment
  namespace: sample
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: days-app
    spec:
      imagePullSecrets:
      - name: github-container-registry-login
      containers:
      - name: days-app-container
        image: ghcr.io/dineshkhannam/gitops01:223db19b5b1a731260e657fcbe1ee5b26a0746c0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
  selector:
    matchLabels:
      app: days-app
