name: Build Step

on:
  push:
    branches: ['dev']
#   pull_request:
#     branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

 # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          context: .
          # Note: tags has to be all lower-case
          tags: |
             #imrishav/gitops01:${{ github.sha }} 
             ghcr.io/dineshkhannam/gitops:${{ github.sha }}
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/dev' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        
  
  update-manifest-stage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: dineshkhannam/testing_repo
          ref: 'kube-manifest'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: setup git config
        run: |
          git config --global user.email "dinesh.khannam@gmail.com"
          git config --global user.name "dineshkhanna"
          echo ${{ github.sha }}
          echo "updated image tag in values file"
          sed -i "s,tag:.*,tag:\${{ github.sha }}," helm/values.yaml
          ## sed -i "s#${{ github.actor }}.*#${{ github.actor }}/gitops01:${{ github.sha }}#g" deployment.yaml
          git add -A
          git commit -am "Update image for - ${{ github.sha }}"
      - run: echo ${{ github }}
      - run: git push origin dev

  
